/*Name: Shawn Ogbomo
Student #:30640218
Date: Friday Feb 5 2021
DBS211 - Lab 03*/

SET AUTOCOMMIT ON;

Question 1 
SELECT * FROM OFFICES; 

Question 2
SELECT
    "A1"."EMPLOYEENUMBER" "EMPLOYEENUMBER"
FROM
    "DBS211_211I14"."EMPLOYEES" "A1"
WHERE
    "A1"."OFFICECODE" = 1
    
Question 3 
SELECT CUSTOMERNUMBER,CUSTOMERNAME,CONTACTFIRSTNAME,CONTACTLASTNAME,PHONE
FROM CUSTOMERS
WHERE CITY = 'Paris'

Question 4 
SELECT CONTACTLASTNAME ||' ' || CONTACTFIRSTNAME
FROM CUSTOMERS
WHERE COUNTRY = 'Canada';

Question 5 
SELECT CUSTOMERNUMBER
FROM PAYMENTS
WHERE AMOUNT > 0

Question 6 
SELECT CUSTOMERNUMBER,CHECKNUMBER,AMOUNT
FROM PAYMENTS 
WHERE AMOUNT NOT BETWEEN 30000 AND 65000
ORDER BY AMOUNT ASC 

Question 7 
SELECT *
FROM ORDERS 
WHERE STATUS = 'Cancelled'
Order By ORDERDATE ASC 

Question 8 
SELECT PRODUCTCODE,PRODUCTNAME,BUYPRICE,MSRP,MSRP-BUYPRICE AS markup,ROUND(100*(MSRP-BUYPRICE)/BuyPrice,2) AS percmarkup
FROM PRODUCTS 

Question 9 
SELECT *
FROM PRODUCTS
WHERE PRODUCTNAME LIKE '%co%' 

Question 10 
SELECT CONTACTFIRSTNAME || ' ' || CONTACTLASTNAME
FROM CUSTOMERS
WHERE LOWER (CONTACTFIRSTNAME) LIKE 's%e%'

Question 11
INSERT INTO EMPLOYEES (EMPLOYEENUMBER, EMAIL, JOBTITLE, OFFICECODE, REPORTSTO, LASTNAME,FIRSTNAME, EXTENSION) 
VALUES(1109, 'sogbomo1@myseneca.ca', 'Cashier', 4, 1088, 'Ogbomo', 'Shawn', 'x99');

Question 12 
SELECT * 
FROM EMPLOYEES 
WHERE EMAIL = 'sogbomo1@myseneca.ca'

Question 13
UPDATE EMPLOYEES
    SET JOBTITLE = 'Head Cashier'
    WHERE EMAIL = 'sogbomo1@myseneca.ca'
    
Question 14
INSERT INTO EMPLOYEES (EMPLOYEENUMBER, EMAIL, JOBTITLE, OFFICECODE, REPORTSTO, LASTNAME,FIRSTNAME, EXTENSION) 
VALUES(2254, 'James-Smith@myseneca.ca', 'Cashier', 4, 1109, 'Smith', 'James', 'x01');

Question 15 
DELETE FROM EMPLOYEES
WHERE EMAIL = 'sogbomo1@myseneca.ca'
/*This command was unsuccessful 
it was unsuccessful because it defies referential integrity 
James is referring to Shawn */

Question 16
DELETE FROM EMPLOYEES
WHERE EMAIL = 'James-Smith@myseneca.ca'
--This statement was successful 

Question 17
    INTO EMPLOYEES VALUES (1109, 'Ogbomo', 'Shawn', 'x99', 'sogbomo1@myseneca.ca', 4, 1088, 'Cashier');
    INTO EMPLOYEES VALUES (2254, 'Smith', 'James', 'x01', 'James-Smith@myseneca.ca', 4, 1109, 'Cashier');
    INTO EMPLOYEES VALUES (NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    SELECT * FROM EMPLOYEES;
Question 18 
DELETE FROM EMPLOYEES
WHERE EMAIL LIKE '%seneca%';

--SELECT *FROM EMPLOYEES;

